# Generated by Django 5.0.6 on 2024-07-06 22:38

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(default=uuid.uuid4, max_length=255, unique=True),
        ),
    ]
