# Generated by Django 5.0.6 on 2024-07-09 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_rename_first_name_user_firstname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='org_id',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
